FROM python:3.12-slim

WORKDIR /neo4j

COPY requirements.txt .
RUN pip install --no-cache-dir neo4j==4.4.13 pandas==3.0.2 python-dotenv==1.2.2 "psycopg[binary]==3.3.4"

COPY . .

CMD ["python", "load_all.py"]
