FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /workspace

RUN pip install --no-cache-dir elasticsearch==8.15.1

COPY app ./app
COPY scripts ./scripts

CMD ["python", "scripts/load_elasticsearch.py"]
