COLOR_TEXT = "#1f2933"
COLOR_MUTED = "#52606d"
COLOR_SURFACE = "#ffffff"
COLOR_BORDER = "#d9e2ec"
COLOR_ACCENT = "#2f80ed"
COLOR_ACCENT_SOFT = "#e8f1ff"
COLOR_BACKGROUND = "#f7f9fc"

CARD_RADIUS_PX = 8
